library(ggplot2)
library(ggplot2movies)
pl <- ggplot(movies,aes(x=rating))
pl2 <- pl+geom_histogram(binwidth = 0.1,aes(fill=..count..))
pl3 <- pl2 + xlab("Movie Rating") + ylab("Count")
print(pl3 + ggtitle("MY TITLE"))